[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "logobert"
version = "0.1.0"
requires-python = ">=3.9"
dependencies = [
  "torch",
  "transformers",
  "datasets",
  "numpy",
  "pandas",
  "scikit-learn",
  "tqdm",
  "wandb",
  "huggingface-hub",
  "biopython",

]

[tool.setuptools]
packages = { find = { include = ["logobert*"] } }
